version: "3"

services:

  postgres:
    image: postgres:14.5
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "POSTGRES_PASSWORD=postgres pg_isready -U postgres"]
      retries: 30
      interval: 5s
      timeout: 5s
    networks:
      innotter_net:

volumes:
  postgres:

networks:
  innotter_net:
    ipam:
      config:
        - subnet: 172.0.0.0/24

