version: "3"

services:

  postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "POSTGRES_PASSWORD=postgres pg_isready -U postgres"]
      retries: 30
      interval: 5s
      timeout: 5s




volumes:
  postgres: