# Generated by Django 4.0.5 on 2022-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("page", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="description",
            field=models.TextField(max_length=180),
        )
    ]
