# Generated by Django 4.0.6 on 2022-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.URLField(blank=True, default='default.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='page', max_length=80),
        ),
    ]
