# Generated by Django 4.0.6 on 2022-08-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_post_reply_to_alter_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='page.page'),
        ),
    ]
